## Observations


- Sent_date column is of string data type
- There are NULLs  in Primary Topic column
- Special characters in Primary Topic column
- Entries observed where email is not opened but link is clicked

## Read Data

In [1]:
import pandas as pd

In [2]:
# Read in the csv

email_path = "../data/Email_Campaign_Details.csv"
# email_df = pd.read_csv(email_path, encoding='cp1252')
email_df = pd.read_csv(email_path, encoding='mac_roman')
email_df.head()

,Email_Campaign_id,contact_id,email_subject,is_sent,is_delivered,is_link_clicked,is_hard_bounce,is_bounce,is_opt_out,is_open,Sent_date,Campaign_type,Primary Topic
0,701200000006cIGAAY,00v2000000IZVYWAA5,Roadshow Houston (Advisor),1,1,0,0,0,0,1,2/7/2023,Events - In Person,/
1,701200000006cIGAAY,00v2000000IZW13AAH,Roadshow Houston (Advisor),1,1,0,0,0,0,1,2/7/2023,Events - In Person,/
2,701200000006cIGAAY,00v2000000IZUepAAH,Roadshow Houston (Advisor),1,1,0,0,0,0,0,2/7/2023,Events - In Person,/
3,701200000006cIGAAY,00v2000000IZWDdAAP,Roadshow Houston (Advisor),1,1,0,0,0,0,0,2/7/2023,Events - In Person,/
4,701200000006cIGAAY,00v2000000IZUdSAAX,Roadshow Houston (Advisor),1,1,0,0,0,0,0,2/7/2023,Events - In Person,/

## Dataframe types and informations

In [3]:
email_df.dtypes

Email_Campaign_id    object
contact_id           object
email_subject        object
is_sent               int64
is_delivered          int64
is_link_clicked       int64
is_hard_bounce        int64
is_bounce             int64
is_opt_out            int64
is_open               int64
Sent_date            object
Campaign_type        object
Primary Topic        object
dtype: object

In [4]:
email_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128236 entries, 0 to 128235
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Email_Campaign_id  128236 non-null  object
 1   contact_id         128236 non-null  object
 2   email_subject      128236 non-null  object
 3   is_sent            128236 non-null  int64
 4   is_delivered       128236 non-null  int64
 5   is_link_clicked    128236 non-null  int64
 6   is_hard_bounce     128236 non-null  int64
 7   is_bounce          128236 non-null  int64
 8   is_opt_out         128236 non-null  int64
 9   is_open            128236 non-null  int64
 10  Sent_date          128236 non-null  object
 11  Campaign_type      128236 non-null  object
 12  Primary Topic      111816 non-null  object
dtypes: int64(7), object(6)
memory usage: 12.7+ MB

In [5]:
email_df.describe(include = 'all')

,Email_Campaign_id,contact_id,email_subject,is_sent,is_delivered,is_link_clicked,is_hard_bounce,is_bounce,is_opt_out,is_open,Sent_date,Campaign_type,Primary Topic
count,128236,128236,128236,128236.0,128236.000000,128236.000000,128236.000000,128236.000000,128236.000000,128236.000000,128236,128236,111816
unique,514,3872,466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,219,6,18
top,70120000000MfxSAAS,00v2000000IZVYWAA5,ETF Review 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6/7/2023,Newsletter,ETF
freq,3778,35,3778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6102,39060,34706
mean,NaN,NaN,NaN,1.0,0.978243,0.004616,0.000686,0.022240,0.000094,0.260036,NaN,NaN,NaN
std,NaN,NaN,NaN,0.0,0.145889,0.067788,0.026187,0.147465,0.009673,0.438656,NaN,NaN,NaN
min,NaN,NaN,NaN,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN

## Duplicate Analysis


- The data seems to have duplicates for Campaign id : "70120000000MfxSAAS"
- Campaign id : "70120000000MfxSAAS" had 2 sent emails
- Upon verification in next section it doesn't seem to be duplicates.

In [6]:
email_df[email_df.duplicated()]

,Email_Campaign_id,contact_id,email_subject,is_sent,is_delivered,is_link_clicked,is_hard_bounce,is_bounce,is_opt_out,is_open,Sent_date,Campaign_type,Primary Topic
29968,70120000000MfxSAAS,00v2000000bnkNcAAI,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
29969,70120000000MfxSAAS,00v2000000bGVGpAAO,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
29970,70120000000MfxSAAS,00v2000000HPhJtAAL,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
29971,70120000000MfxSAAS,00v2000000RD8MHAA1,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
29972,70120000000MfxSAAS,00v2000000U2zWUAAZ,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30315,70120000000MfxSAAS,00v2000000MinpkAAB,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
30316,70120000000MfxSAAS,00v2000000MjeypAAB,ETF Review 8,1,1,0,0,0,0,1,8/1/2023,Newsletter,ETF
30317,70120000000MfxSAAS,00v2000000NawFcAAJ,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
30318,70120000000MfxSAAS,00v2000000NavbNAAR,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
30319,70120000000MfxSAAS,00v2000000OSMa3AAH,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF

In [7]:
email_df[(email_df["Email_Campaign_id"] == "70120000000MfxSAAS") \
& (email_df["contact_id"] == "00v2000000bnkNcAAI")]

,Email_Campaign_id,contact_id,email_subject,is_sent,is_delivered,is_link_clicked,is_hard_bounce,is_bounce,is_opt_out,is_open,Sent_date,Campaign_type,Primary Topic
26544,70120000000MfxSAAS,00v2000000bnkNcAAI,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
29968,70120000000MfxSAAS,00v2000000bnkNcAAI,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF

In [8]:
email_df[(email_df["Email_Campaign_id"] == "70120000000MfxSAAS") \
& (email_df["contact_id"] == "00v2000000WNg0kAAD")]

,Email_Campaign_id,contact_id,email_subject,is_sent,is_delivered,is_link_clicked,is_hard_bounce,is_bounce,is_opt_out,is_open,Sent_date,Campaign_type,Primary Topic
26880,70120000000MfxSAAS,00v2000000WNg0kAAD,ETF Review 8,1,1,0,0,0,0,0,8/1/2023,Newsletter,ETF
30304,70120000000MfxSAAS,00v2000000WNg0kAAD,ETF Review 8,1,1,0,0,0,0,1,8/1/2023,Newsletter,ETF

## Value Counts for columns / dimensions

In [9]:
email_df["Campaign_type"].value_counts()

Campaign_type
Newsletter                 39060
Marketing Campaign         32026
Event follow up            22497
Digital event              16538
Events - In Person         10024
Marketing Communication     8091
Name: count, dtype: int64

In [10]:
email_df["Primary Topic"].value_counts()

Primary Topic
ETF                34706
Bonds              14321
Portfolio          13840
Market Insights    13226
Ad hoc              8632
Adhoc               7167
Equities            6514
Insights            5326
HealthCare          4943
Asssets             1095
Funds                814
Income               465
Investment           449
Retirement           187
Asset                 61
--                    39
/                     25
Growth                 6
Name: count, dtype: int64

## Special Characters in Primary Topic Column

- / Primary topic entries are similar to NULL Primary Topics in similar email subjects.
- "- -" Primary topic entries are similar to NULL Primary Topics in similar email subjects.

In [11]:
email_df[email_df["Primary Topic"] == "/"].head()

,Email_Campaign_id,contact_id,email_subject,is_sent,is_delivered,is_link_clicked,is_hard_bounce,is_bounce,is_opt_out,is_open,Sent_date,Campaign_type,Primary Topic
0,701200000006cIGAAY,00v2000000IZVYWAA5,Roadshow Houston (Advisor),1,1,0,0,0,0,1,2/7/2023,Events - In Person,/
1,701200000006cIGAAY,00v2000000IZW13AAH,Roadshow Houston (Advisor),1,1,0,0,0,0,1,2/7/2023,Events - In Person,/
2,701200000006cIGAAY,00v2000000IZUepAAH,Roadshow Houston (Advisor),1,1,0,0,0,0,0,2/7/2023,Events - In Person,/
3,701200000006cIGAAY,00v2000000IZWDdAAP,Roadshow Houston (Advisor),1,1,0,0,0,0,0,2/7/2023,Events - In Person,/
4,701200000006cIGAAY,00v2000000IZUdSAAX,Roadshow Houston (Advisor),1,1,0,0,0,0,0,2/7/2023,Events - In Person,/

In [12]:
email_df[email_df["email_subject"].str.contains("Roadshow")] \
["Primary Topic"].value_counts()

Primary Topic
Ad hoc    1296
/           15
Name: count, dtype: int64

In [13]:
email_df[(email_df["email_subject"].str.contains("Roadshow")) \
& (email_df["Primary Topic"].isnull())] \
["email_subject"].value_counts()

email_subject
Roadshow Atlanta (PS)            2343
Roadshow  NYC (PS)               2067
Roadshow  Boston (PS)             972
Roadshow  Detroit (PS)            432
Roadshow Houston (PS)              90
Roadshow Washington (Advisor)       7
Name: count, dtype: int64

In [14]:
email_df[(email_df["email_subject"].str.contains("Roadshow")) \
& (email_df["Primary Topic"].notnull())] \
["email_subject"].value_counts()

email_subject
Roadshow Houston (PS) Feedback!    1296
Roadshow Houston (Advisor)           15
Name: count, dtype: int64

In [15]:
email_df[email_df["email_subject"] == "Roadshow Houston (PS) Feedback!"] \
["Primary Topic"].value_counts()

Primary Topic
Ad hoc    1296
Name: count, dtype: int64

In [16]:
email_df[email_df["email_subject"].str.contains("Brief outlook")] \
["Primary Topic"].value_counts()

Primary Topic
Portfolio          877
Market Insights    176
Retirement          65
Funds               53
HealthCare          19
Equities            14
/                   10
Investment          10
Income               4
Asssets              2
Growth               1
Name: count, dtype: int64

In [17]:
email_df[email_df["email_subject"].str.contains("Brief outlook")] \
[["email_subject", "Primary Topic"]].value_counts()

email_subject                         Primary Topic
Brief outlook on Portfolio Analytics  Portfolio          495
Brief outlook on Portfolio Insights   Portfolio          382
Brief outlook on Market Commentary    Market Insights    169
Brief outlook on Retirement Link      Retirement          65
Brief outlook on Investor Funds       Funds               44
Brief outlook on Healthcare           HealthCare          19
Brief outlook on Equities             Equities            14
Brief outlook on Real Estate          /                   10
Brief outlook on Hedge Funds          Funds                9
Brief outlook on Investment Forum     Investment           9
Brief outlook on MI-Market Insights   Market Insights      6
Brief outlook on Income               Income               4
Brief outlook on Asset Allocation     Asssets              2
Brief outlook on Emerging Markets     Market Insights      1
Brief outlook on Growth               Growth               1
Brief outlook on Investment Trust     Investment           1
Name: count, dtype: int64

In [18]:
email_df[(email_df["email_subject"].str.contains("Real Estate")) \
& (email_df["Primary Topic"].isnull())] \
[["email_subject"]].value_counts()

email_subject
Topic of the month Real Estate    14
Brief outlook on Real Estate       3
Name: count, dtype: int64

In [19]:
# for -- primary topic

email_df[email_df["Primary Topic"] == "--"].head()

,Email_Campaign_id,contact_id,email_subject,is_sent,is_delivered,is_link_clicked,is_hard_bounce,is_bounce,is_opt_out,is_open,Sent_date,Campaign_type,Primary Topic
12980,70120000000Lp3eAAC,00v2000000KLpp3AAD,pharma Insights 2023,1,1,0,0,0,0,1,10/4/2023,Marketing Campaign,--
12981,70120000000Lp3eAAC,00v2000000KKbuRAAT,pharma Insights 2023,1,1,0,0,0,0,0,10/4/2023,Marketing Campaign,--
12982,70120000000Lp3eAAC,00v2000000KLfRoAAL,pharma Insights 2023,1,1,0,0,0,0,0,10/4/2023,Marketing Campaign,--
12983,70120000000Lp3eAAC,00v2000000KLfmGAAT,pharma Insights 2023,1,1,0,0,0,0,1,10/4/2023,Marketing Campaign,--
12984,70120000000Lp3eAAC,00v2000000KMMtsAAH,pharma Insights 2023,1,1,0,0,0,0,0,10/4/2023,Marketing Campaign,--

In [20]:
email_df[(email_df["email_subject"].str.contains("pharma Insights")) \
& (email_df["Primary Topic"].isnull())]

,Email_Campaign_id,contact_id,email_subject,is_sent,is_delivered,is_link_clicked,is_hard_bounce,is_bounce,is_opt_out,is_open,Sent_date,Campaign_type,Primary Topic
12950,70120000000Lp3eAAC,00v2000000KLfjTAAT,pharma Insights 2023,1,1,0,0,0,0,0,10/4/2023,Marketing Campaign,NaN
12951,70120000000Lp3eAAC,00v2000000KLfrfAAD,pharma Insights 2023,1,1,0,0,0,0,0,10/4/2023,Marketing Campaign,NaN
12952,70120000000Lp3eAAC,00v2000000KLufUAAT,pharma Insights 2023,1,1,0,0,0,0,0,10/4/2023,Marketing Campaign,NaN
12953,70120000000Lp3eAAC,00v2000000KLvA9AAL,pharma Insights 2023,1,1,0,0,0,0,0,10/4/2023,Marketing Campaign,NaN
12954,70120000000Lp3eAAC,00v2000000KLvc6AAD,pharma Insights 2023,1,1,0,0,0,0,0,10/4/2023,Marketing Campaign,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96285,701D0000000NCYqIAO,00v2000000KNylxAAD,pharma Insights Q3,1,1,0,0,0,0,0,1/11/2023,Marketing Campaign,NaN
96286,701D0000000NCYqIAO,00v2000000KNz45AAD,pharma Insights Q3,1,1,0,0,0,0,0,1/11/2023,Marketing Campaign,NaN
96287,701D0000000NCYqIAO,00v2000000KXTkYAAX,pharma Insights Q3,1,1,0,0,0,0,0,1/11/2023,Marketing Campaign,NaN
96288,701D0000000NCYqIAO,00v2000000KXUhXAAX,pharma Insights Q3,1,1,0,0,0,0,1,1/11/2023,Marketing Campaign,NaN
96289,701D0000000NCYqIAO,00v2000000KXiypAAD,pharma Insights Q3,1,1,0,0,0,0,1,1/11/2023,Marketing Campaign,NaN

## Primary Topic - Ad hoc VS Adhoc

- Rename them to "Adhoc Invitation" and "Adhoc Feedback". But, after investigation on other Primary Topics no bifurcation is needed.

In [21]:
email_df[(email_df["Primary Topic"] == "Ad hoc")]["email_subject"].value_counts()

email_subject
Thanks for attending  Defined Contribution Fund Session                         1843
Thanks for attending  Defined Benefit Fund Session                              1774
Roadshow Houston (PS) Feedback!                                                 1296
Thanks for attending  Alternatives Stratergy Session                            1221
Thanks for attending  Defined Benefit Stratergy Session                          870
You are Invited! Defined Contribution Discussion 2023                            613
European CEOs Summit Feedback!                                                   432
Thanks for attending  Tax Management Stratergy Session                           270
Your Feedback is important- tell us more on  Infrastructure Insights Session     197
Thanks for attending  Employee Fund Session                                       45
London CIO Roundtable - Feedback!                                                 15
Thanks for attending  Defined Contribution Stratergy Session                      13
APAC Summit 2023 Feedback!                                                        12
Thanks for attending  Employee Stratergy Session                                  10
Your Feedback is important- tell us more on  pharma Insights Session               9
Thanks for attending  Alternatives Fund Session                                    7
Thanks for attending  Tax Management fund Session                                  4
Invstment Acadmey  Feedback!                                                       1
Name: count, dtype: int64

In [22]:
email_df[(email_df["Primary Topic"] == "Adhoc")]["email_subject"].value_counts()

email_subject
Invitation to  Defined Contribution                                              2805
Invitation to  Employee Fund                                                     2606
Meeting for  Product fund Insights                                                781
Invitation to  Global Liquidity                                                   387
We are looking forward to seeing you in Birmingham next week                      286
Meeting for  Fund Insights                                                        108
You are Invited! Global Liquidity Discussion 2023                                  37
Webinar Invite on   Insights Tool                                                  33
Virtual Invitation to attend web conference on Alternatives Stratergy              22
Virtual Invitation to attend web conference on Tax Management fund                 22
Virtual Invitation to attend web conference on Defined Benefit Fund                22
Virtual Invitation to attend web conference on Alternatives Fund                   20
Virtual Invitation to attend web conference on Defined Contribution Fund           19
Meeting for  Brief Fund Management                                                  7
Virtual Invitation to attend web conference on Defined Benefit Stratergy            5
Virtual Invitation to attend web conference on Employee Stratergy                   4
Virtual Invitation to attend web conference on Employee Fund                        1
You are Invited! Employee Discussion 2023                                           1
Virtual Invitation to attend web conference on Defined Contribution Stratergy       1
Name: count, dtype: int64

In [23]:
email_df[email_df["Primary Topic"] == "Market Insights"]["email_subject"].value_counts()

email_subject
Invitation to  Eye on the Market                                                            3531
Virtual Invitation to attend web conference on Market Commentary fund                       2224
Thanks for attending  Market Commentary Stratergy Session                                   2077
Virtual Invitation to attend web conference on Long Term Capital Market Assumptions fund    1798
BI Weekly update on Emerging Markets                                                         694
Whats Happening around Market Insights Stratergy                                             625
Thanks for attending  Market Commentary fund Session                                         590
Thanks for attending  Market Insights fund Session                                           478
Market Insights fund trending this year!                                                     377
Brief outlook on Market Commentary                                                           169
Whats Happening around Market Commentary fund                                                132
Meeting for  Weekly Market Knowledge News                                                     80
Whats Happening around Market Insights fund                                                   78
Whats Happening around Long Term Capital Market Assumptions fund                              74
Thanks for attending  Long Term Capital Market Assumptions Stratergy Session                  50
Meeting for  Market Update                                                                    50
Whats Happening around Long Term Capital Market Assumptions Stratergy                         35
BI Weekly update on MI-Market Insights                                                        26
Market Commentary fund trending this year!                                                    14
Thanks for attending  Long Term Capital Market Assumptions fund Session                       12
Topic of the month Emerging Markets                                                           12
Webinar Invite on  Market Insights Bulletin                                                   12
BI Weekly update on Market Commentary                                                          9
Whats Happening around Market Commentary Stratergy                                             8
You are Invited! Market Commentary Discussion 2023                                             8
You are Invited! Guide to the Markets Discussion 2023                                          7
Long Term Capital Market Assumptions Stratergy trending this year!                             7
Monthly Fund Review - Take on  Market Commentary fund                                          6
Brief outlook on MI-Market Insights                                                            6
You are Invited! Long Term Capital Market Assumptions Discussion 2023                          5
You are Invited! Market Insights Discussion 2023                                               4
Topic of the month MI-Market Insights                                                          4
You are Invited! Eye on the Market Discussion 2023                                             3
Monthly Fund Review - Take on  Market Insights fund                                            3
Webinar Invite on  Market Commentary Outlook                                                   3
Thanks for attending  Market Insights Stratergy Session                                        3
Topic of the month Market Commentary                                                           3
Market Insights Stratergy trending this year!                                                  2
Webinar Invite on  Long Term Capital Market Assumptions                                        2
Long Term Capital Market Assumptions fund trending this year!                                  1
You are Invited! Weekly Market Recap Discussion 2023                                           1
Brief outlook on Emerging Markets                                                              1
Market Commentary Stratergy trending this year!                                                1
Monthly Fund Review - Take on  Long Term Capital Market Assumptions fund                       1
Name: count, dtype: int64

## Check flag columns

Journey

- sent
- delivered - bounced
- open
- link clicked / opt out

There are three entries with improper sequence of email opening. Probaly bad data. There were two options: either remove the 3 rows or correct the data. This analysis takes the approach of removing those columns as volume of data is very less.

In [24]:
email_df[(email_df["is_sent"] == 0) \
& (email_df["is_delivered"] == 1)]

Empty DataFrame
Columns: [Email_Campaign_id, contact_id, email_subject, is_sent, is_delivered, is_link_clicked, is_hard_bounce, is_bounce, is_opt_out, is_open, Sent_date, Campaign_type, Primary Topic]
Index: []

In [25]:
email_df[(email_df["is_sent"] == 0) \
& (email_df["is_delivered"] == 0) \
& (email_df["is_open"] == 1)]

Empty DataFrame
Columns: [Email_Campaign_id, contact_id, email_subject, is_sent, is_delivered, is_link_clicked, is_hard_bounce, is_bounce, is_opt_out, is_open, Sent_date, Campaign_type, Primary Topic]
Index: []

In [26]:
email_df[(email_df["is_sent"] == 0) \
& (email_df["is_delivered"] == 0) \
& (email_df["is_bounce"] == 1)]

Empty DataFrame
Columns: [Email_Campaign_id, contact_id, email_subject, is_sent, is_delivered, is_link_clicked, is_hard_bounce, is_bounce, is_opt_out, is_open, Sent_date, Campaign_type, Primary Topic]
Index: []

In [27]:
email_df[["is_bounce", "is_hard_bounce"]].value_counts()

is_bounce  is_hard_bounce
0          0                 125384
1          0                   2764
           1                     88
Name: count, dtype: int64

In [28]:
email_df[["is_open", "is_link_clicked"]].value_counts()

is_open  is_link_clicked
0        0                  94887
1        0                  32757
         1                    589
0        1                      3
Name: count, dtype: int64

In [29]:
email_df[["is_open", "is_link_clicked", "is_opt_out"]].value_counts()

is_open  is_link_clicked  is_opt_out
0        0                0             94887
1        0                0             32757
         1                0               577
                          1                12
0        1                0                 3
Name: count, dtype: int64

In [30]:
# email_df[email_df["is_delivered"] == 1][["is_bounce"]]

email_df[["is_delivered", "is_bounce", "is_hard_bounce"]].value_counts().sort_index()

is_delivered  is_bounce  is_hard_bounce
0             1          0                   2702
                         1                     88
1             0          0                 125384
              1          0                     62
Name: count, dtype: int64

## Primary Topic NULL

- There are different ways of handling this issue. Remove it "OR" assign it a category "OR" based on string match assign new custom category

In [31]:
email_df[email_df["Primary Topic"].isnull()]["email_subject"].value_counts(normalize=True).head(20)

email_subject
Roadshow Atlanta (PS)                          0.142692
Women's Summit Q4                              0.139829
Roadshow  NYC (PS)                             0.125883
Alternatives Stratergy trending this year!     0.117235
Roadshow  Boston (PS)                          0.059196
Take on  Employee Stratergy                    0.055847
Employee Fund Update this year!                0.055481
Alternatives Fund Update this year!            0.047503
European CEOs Summit                           0.036054
London CIO Roundtable                          0.033313
Info on  Defined Benefit Stratergy             0.029050
pharma Insights 2023                           0.028989
Roadshow  Detroit (PS)                         0.026309
Brief outlook on Absolute return               0.022838
Brief outlook on Absolute Return               0.011206
Brief outlook on Liquidity Insights            0.009805
Focus on  Tax Management fund                  0.007613
Defined Contribution Fund Update this year!    0.006943
Roadshow Houston (PS)                          0.005481
Brief outlook on Defined Benefit               0.004689
Name: proportion, dtype: float64